name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_check:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a recent LTS version of Node.js

      # Install only Prettier
      - name: Install Prettier
        run: npm install prettier --save-dev

      - name: Check Formatting with Prettier
        run: npx prettier --check .
        # This checks if files match Prettier's formatting rules based on your config.
